version: "3"
services:
  snippy:
    image: node
    volumes:
      - ./build:/app
    command: bash -c "cd /app && node ."
    env_file:
      - .env
  snippy_ai:
    image: python
    volumes:
      - ./build:/app
    env_file:
      - .env
